CXX=g++
CXXFLAGS=-std=c++17 -g -pedantic -Wall -Wextra -Werror -fsanitize=address,undefined -fno-omit-frame-pointer
LDLIBS=


SRCS=server.cpp client.cpp
DEPS=BoundedBuffer.cpp common.cpp FIFORequestChannel.cpp Histogram.cpp HistogramCollection.cpp
BINS=$(SRCS:%.cpp=%.exe)
OBJS=$(DEPS:%.cpp=%.o)


all: clean $(BINS)

%.o: %.cpp %.h
	$(CXX) $(CXXFLAGS) -c -o $@ $<

%.exe: %.cpp $(OBJS)
	$(CXX) $(CXXFLAGS) -o $(patsubst %.exe,%,$@) $^ $(LDLIBS)


.PHONY: clean test

clean:
	rm -f server client fifo* data*_* *.tst *.o *.csv received/*

test: all
	chmod u+x pa3-tests.sh
	./pa3-tests.sh
